### ISSUE TITLE
What would be the easiest way to get all the chords for a set of notes?

### ISSUE THREAD

**Issue by McOmghall** [jsrmath/sharp11#2]
Does this library have any such facility to get all the possible chords from a note set?

**Comment by jsrmath** [comment]
The way Sharp11 is structured is to produce the best possible chord spelling for any particular set of notes with `s11.chord.identify(...)`. I figured in most cases people would just want one result, but I'm curious as to what you would want this feature for.

**Comment by McOmghall** [comment]
I'm building both a web ear trainer and a composition tool that gives you all the scales and chords you can use with a given set of notes. I've read the code for `.identify` and I think it'd be better if, optionally, you could get all the chords it generates. I've replicated this functionality on my own code copying your functions though.

**Comment by jsrmath** [comment]
So does it just return all "reasonable" inversions? That's a pretty easy change to add and I might do it if you think that's sufficient for what you're trying to do. As for getting all possible scales for a set of notes, the `.scales` method on chord objects does just that.

**Comment by McOmghall** [comment]
I've found the `.scales` method only returns "reasonable" scales as well (i.e. for `{C, D, Eb, G}` only returns scales in `C`), so I constructed all the possible scales and filtered by all scales that contain my set of pitches. As for the chords set I'm currently working with your `tryInversion` method, that returns the chord symbol for any given inversion, that's enough for me. I wouldn't want the "reasonable" inversions only because being a composition tool should give you all the possibilities, I think.

Therefore, I believe you don't need to include this in your library since I managed to do it outside it, but might be useful to other people.

**Comment by jsrmath** [comment]
`.scales` only returns scales with the same root as the chord it's called on and I intend to keep it that way, but you could call it on every inversion to get every possible scale. That said, you'll get a lot of different names for the same scale by nature of how modes work.
